<?php

namespace Berd\EventLogsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TableEventLogsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TableEventLogsRepository extends EntityRepository
{
}
