<?php

namespace Berd\PersonnageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemsRepository extends EntityRepository
{
   public function afficherUnPersonnage($id)
  {
	   return $this->_em->createQuery('SELECT p FROM PersonnageBundle:Personnage p
	   WHERE p.id = :id
	   ')
	   ->setParameter('id', $id)->getQuery();
  }
}
