<?php

namespace Berd\PersonnageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SacRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SacRepository extends EntityRepository
{
}
