<?php

namespace Berd\DashboardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ParamsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParamsRepository extends EntityRepository
{
	public function recupererParametre($id){
	    
		$query = $this->getEntityManager()
               ->createQuery('SELECT p FROM DashboardBundle:Params p WHERE Id= :id ')
		->setParameter('id', $id);
		
		$resultatParametre = $query->getSingleResult();
		
        return $resultatParametre;
	}
}
