<?php

namespace Berd\DashboardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ResultsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultsRepository extends EntityRepository
{
}
