berd_personnage_personnage:
    resource: "@BerdPersonnageBundle/Resources/config/routing/personnage.yml"
    prefix:   /personnage

berd_personnage_sac:
    resource: "@BerdPersonnageBundle/Resources/config/routing/sac.yml"
    prefix:   /sac

berd_personnage_items:
    resource: "@BerdPersonnageBundle/Resources/config/routing/items.yml"
    prefix:   /items

berd_personnage_afficher:
    pattern: /afficher/ 
    defaults: {_controller:BerdPersonnageBundle:Personnage:afficher}

berd_personnage_recuperer:
    pattern: /recuperer/{id}
    defaults: {_controller:BerdPersonnageBundle:Personnage:recuperer}

berd_personnage_creer:
    pattern: /creer/
    defaults: {_controller:BerdPersonnageBundle:Personnage:creer}

berd_personnage_defaut:
    pattern: /defaut/
    defaults: {_controller:BerdPersonnageBundle:Default:index}
